/* Automatically generated by wasm2c */
#ifndef MINO_H_GENERATED_
#define MINO_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs;

typedef struct w2c_mino {
  struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs* w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
  wasm_rt_externref_table_t w2c_0x5F_wbindgen_export_2;
} w2c_mino;

void wasm2c_mino_instantiate(w2c_mino*, struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);
void wasm2c_mino_free(w2c_mino*);
wasm_rt_func_type_t wasm2c_mino_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_call_672a4d21634d4a24' */
wasm_rt_externref_t w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_call_672a4d21634d4a24(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_document_d249400bd7bd996d' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_document_d249400bd7bd996d(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_drawImage_07c37f8560e58bbd' */
void w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_drawImage_07c37f8560e58bbd(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, f64, f64, f64, f64, f64, f64, f64, f64);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_innerHTML_e1553352fe93921a' */
void w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_innerHTML_e1553352fe93921a(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_instanceof_Window_def73ea0955fc569' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_instanceof_Window_def73ea0955fc569(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_newnoargs_105ed471475aaf50' */
wasm_rt_externref_t w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_newnoargs_105ed471475aaf50(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_querySelector_c69f8b573958906b' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_querySelector_c69f8b573958906b(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t, u32, u32);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_static_accessor_GLOBAL_88a902d13a557d07' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_88a902d13a557d07(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_static_accessor_SELF_37c5d418e4bf5819' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_static_accessor_SELF_37c5d418e4bf5819(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_static_accessor_WINDOW_5de37043a91a9c40' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_static_accessor_WINDOW_5de37043a91a9c40(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);

/* import: '.\2Fdrm_tool_bg.js' '__wbg_width_4f334fc47ef03de1' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbg_width_4f334fc47ef03de1(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbindgen_debug_string' */
void w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbindgen_debug_string(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbindgen_init_externref_table' */
void w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbindgen_init_externref_table(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*);

/* import: '.\2Fdrm_tool_bg.js' '__wbindgen_is_undefined' */
u32 w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbindgen_is_undefined(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fdrm_tool_bg.js' '__wbindgen_throw' */
void w2c_0x2E0x2Fdrm__tool__bg0x2Ejs_0x5F_wbindgen_throw(struct w2c_0x2E0x2Fdrm__tool__bg0x2Ejs*, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_mino_memory(w2c_mino* instance);

/* export: 'render_image' */
void w2c_mino_render_image(w2c_mino*, wasm_rt_externref_t, wasm_rt_externref_t, u32, u32);

/* export: '__wbindgen_exn_store' */
void w2c_mino_0x5F_wbindgen_exn_store(w2c_mino*, u32);

/* export: '__externref_table_alloc' */
u32 w2c_mino_0x5F_externref_table_alloc(w2c_mino*);

/* export: '__wbindgen_export_2' */
wasm_rt_externref_table_t* w2c_mino_0x5F_wbindgen_export_2(w2c_mino* instance);

/* export: '__wbindgen_malloc' */
u32 w2c_mino_0x5F_wbindgen_malloc(w2c_mino*, u32, u32);

/* export: '__wbindgen_realloc' */
u32 w2c_mino_0x5F_wbindgen_realloc(w2c_mino*, u32, u32, u32, u32);

/* export: '__wbindgen_start' */
void w2c_mino_0x5F_wbindgen_start(w2c_mino*);

#ifdef __cplusplus
}
#endif

#endif  /* MINO_H_GENERATED_ */
