/* Automatically generated by wasm2c */
#ifndef MIMI_DESCRAMBLE_H_GENERATED_
#define MIMI_DESCRAMBLE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs;

typedef struct w2c_mimi__descramble {
  struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs* w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_mimi__descramble;

void wasm2c_mimi__descramble_instantiate(w2c_mimi__descramble*, struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*);
void wasm2c_mimi__descramble_free(w2c_mimi__descramble*);
wasm_rt_func_type_t wasm2c_mimi__descramble_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_call_13410aac570ffff7' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_call_13410aac570ffff7(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_clearRect_448c93ecc652d129' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_clearRect_448c93ecc652d129(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, f64, f64, f64, f64);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_document_7d29d139bd619045' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_document_7d29d139bd619045(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_drawImage_8d002fb55b838415' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_drawImage_8d002fb55b838415(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32, f64, f64, f64, f64, f64, f64, f64, f64);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_drawImage_ac6a1d25efb31742' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_drawImage_ac6a1d25efb31742(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32, f64, f64, f64, f64);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_getContext_15e158d04230a6f6' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_getContext_15e158d04230a6f6(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_getElementById_3c3d00d9a16a01dd' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_getElementById_3c3d00d9a16a01dd(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_instanceof_CanvasRenderingContext2d_8c616198ec03b12f' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_instanceof_CanvasRenderingContext2d_8c616198ec03b12f(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_instanceof_HtmlCanvasElement_299c60950dbb3428' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_instanceof_HtmlCanvasElement_299c60950dbb3428(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_instanceof_Window_12d20d558ef92592' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_instanceof_Window_12d20d558ef92592(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_newnoargs_254190557c45b4ec' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_newnoargs_254190557c45b4ec(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_setheight_4fce583024b2d088' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_setheight_4fce583024b2d088(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_setwidth_40a6ed203b92839d' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_setwidth_40a6ed203b92839d(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_static_accessor_GLOBAL_8921f820c2ce3f12' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_8921f820c2ce3f12(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_static_accessor_GLOBAL_THIS_f0a4409105898184' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_THIS_f0a4409105898184(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_static_accessor_SELF_995b214ae681ff99' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_static_accessor_SELF_995b214ae681ff99(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_static_accessor_WINDOW_cde3890479c675ea' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_static_accessor_WINDOW_cde3890479c675ea(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_wbindgenisundefined_c4b71d073b92f3c5' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_wbindgenisundefined_c4b71d073b92f3c5(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbg_wbindgenthrow_451ec1a8469d7eb6' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbg_wbindgenthrow_451ec1a8469d7eb6(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbindgen_cast_2241b6af4c4b2941' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbindgen_cast_2241b6af4c4b2941(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbindgen_object_clone_ref' */
u32 w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbindgen_object_clone_ref(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* import: '.\2Fdescramble_wasm_bg.js' '__wbindgen_object_drop_ref' */
void w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs_0x5F_wbindgen_object_drop_ref(struct w2c_0x2E0x2Fdescramble__wasm__bg0x2Ejs*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_mimi__descramble_memory(w2c_mimi__descramble* instance);

/* export: 'descramble_image' */
void w2c_mimi__descramble_descramble_image(w2c_mimi__descramble*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: '__wbindgen_export_0' */
void w2c_mimi__descramble_0x5F_wbindgen_export_0(w2c_mimi__descramble*, u32);

/* export: '__wbindgen_add_to_stack_pointer' */
u32 w2c_mimi__descramble_0x5F_wbindgen_add_to_stack_pointer(w2c_mimi__descramble*, u32);

/* export: '__wbindgen_export_1' */
u32 w2c_mimi__descramble_0x5F_wbindgen_export_1(w2c_mimi__descramble*, u32, u32);

/* export: '__wbindgen_export_2' */
u32 w2c_mimi__descramble_0x5F_wbindgen_export_2(w2c_mimi__descramble*, u32, u32, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* MIMI_DESCRAMBLE_H_GENERATED_ */
