package eu.kanade.tachiyomi.extension.vi.luvevaland

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    Filter.Header("Lưu ý: Không dùng được khi tìm kiếm bằng tên"),
    GenreFilter(getGenreList()),
    StatusFilter(),
    SortByFilter(),
    SortOrderFilter(),
)

class Genre(name: String, val value: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Tag", genres) {
    fun selectedValues(): List<String> = state.filter { it.state }.map { it.value }
}

open class UriPartFilter(
    displayName: String,
    private val options: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, options.map { it.first }.toTypedArray()) {
    fun toUriPart(): String = options[state].second
}

class StatusFilter :
    UriPartFilter(
        "Trạng thái",
        arrayOf(
            Pair("Tất Cả", ""),
            Pair("Raw", "1"),
            Pair("Chưa hoàn", "2"),
            Pair("Hoàn thành", "3"),
            Pair("Drop", "4"),
        ),
    )

class SortByFilter :
    UriPartFilter(
        "Sắp xếp",
        arrayOf(
            Pair("Ngày cập nhật", "updated_at"),
            Pair("Tên", "name"),
            Pair("Lượt xem", "views"),
            Pair("Số chương", "number_chapter"),
        ),
    )

class SortOrderFilter :
    UriPartFilter(
        "Thứ tự",
        arrayOf(
            Pair("Giảm dần", "desc"),
            Pair("Tăng dần", "asc"),
        ),
    )

private fun getGenreList(): List<Genre> = listOf(
    Genre("1Vs1", "72"),
    Genre("419", "75"),
    Genre("Bách hợp", "7"),
    Genre("Bàn tay vàng", "44"),
    Genre("Báo thù rửa hận", "46"),
    Genre("BE", "119"),
    Genre("BP", "151"),
    Genre("Cán bộ cao cấp", "98"),
    Genre("Cận đại", "16"),
    Genre("Cẩu huyết", "57"),
    Genre("Chữa lành - cứu rỗi", "162"),
    Genre("Chuyển thể", "154"),
    Genre("Có baby", "136"),
    Genre("Cổ đại", "15"),
    Genre("Cổ xuyên kim", "155"),
    Genre("Con cưng của trời", "41"),
    Genre("Cưng chiều", "109"),
    Genre("Cung đấu", "65"),
    Genre("Cung đình hầu tước", "61"),
    Genre("Cưới trước yêu sau", "42"),
    Genre("Dân quốc", "17"),
    Genre("DC", "150"),
    Genre("Dị giới", "85"),
    Genre("Dị năng", "128"),
    Genre("Dưỡng thê - Nuôi vợ từ bé", "60"),
    Genre("Duyên trời tác hợp", "43"),
    Genre("Đại thúc vs loli - Chênh lệch tuổi tác", "59"),
    Genre("Đam mỹ", "6"),
    Genre("Điền văn", "63"),
    Genre("Đô thị tình duyên", "49"),
    Genre("Đoản văn", "19"),
    Genre("eSport - Thể thao điện tử", "55"),
    Genre("Fake Inc", "71"),
    Genre("Fanfic", "144"),
    Genre("Fragonard", "149"),
    Genre("GE", "121"),
    Genre("Gia đấu - Trạch đấu", "64"),
    Genre("Giang hồ", "67"),
    Genre("Gương vỡ không lành", "182"),
    Genre("Gương vỡ lại lành", "47"),
    Genre("Hài hước", "113"),
    Genre("Hào môn thế gia", "39"),
    Genre("HE", "117"),
    Genre("Hệ liệt", "24"),
    Genre("Hệ thống", "91"),
    Genre("Hiện đại", "14"),
    Genre("Hóa thú", "132"),
    Genre("Hoán đổi linh hồn", "116"),
    Genre("Huyền Huyễn", "93"),
    Genre("Inc", "70"),
    Genre("Khống", "83"),
    Genre("Không CP", "8"),
    Genre("Kiếp trước kiếp này", "115"),
    Genre("Kinh dị", "105"),
    Genre("Lạc Miêu Team", "159"),
    Genre("Lâu ngày gặp lại", "177"),
    Genre("Lâu ngày sinh tình", "131"),
    Genre("Lịch sử", "89"),
    Genre("Linh dị thần quái", "124"),
    Genre("Manga", "167"),
    Genre("Mạt thế", "84"),
    Genre("Mất trí nhớ", "185"),
    Genre("Mỹ nhân ngư (Nam/Nữ)", "184"),
    Genre("Mỹ nhân sườn xám", "180"),
    Genre("Mỹ Thực", "53"),
    Genre("Nam cường", "78"),
    Genre("Nam phụ thượng vị - Đập chậu cướp hoa", "174"),
    Genre("Nam trọng sinh", "176"),
    Genre("Nam/nữ có bệnh", "129"),
    Genre("Nam/nữ khiếm khuyết", "133"),
    Genre("Ngây thơ", "77"),
    Genre("Nghiệp giới tinh anh", "143"),
    Genre("Ngôn Tình", "168"),
    Genre("Ngọt", "123"),
    Genre("Ngược", "114"),
    Genre("Ngược luyến tàn tâm", "30"),
    Genre("Ngược luyến tình thâm", "29"),
    Genre("Ngược nam", "32"),
    Genre("Ngược nữ", "33"),
    Genre("Ngược thân", "31"),
    Genre("Ngược tra", "82"),
    Genre("Nham hiểm", "76"),
    Genre("Nhân thú", "90"),
    Genre("Nhất kiến chung tình", "48"),
    Genre("Nhẹ nhàng", "135"),
    Genre("Novel Kr", "187"),
    Genre("NP", "69"),
    Genre("NTR", "165"),
    Genre("Nữ cường", "79"),
    Genre("Nữ giả nam", "141"),
    Genre("Nữ phụ văn", "36"),
    Genre("Nữ tôn", "37"),
    Genre("Nữ truy", "81"),
    Genre("Oan gia", "58"),
    Genre("OE", "120"),
    Genre("On Going", "1"),
    Genre("Phản xuyên", "26"),
    Genre("Quân nhân/Cảnh sát/Đặc công", "97"),
    Genre("Sạch", "68"),
    Genre("SE", "118"),
    Genre("Shoujo", "163"),
    Genre("Showbiz", "102"),
    Genre("Song trùng sinh", "51"),
    Genre("Song xuyên", "158"),
    Genre("Tâm lý", "104"),
    Genre("Tản văn", "20"),
    Genre("Thâm tình", "111"),
    Genre("Thanh mai trúc mã", "96"),
    Genre("Thanh thuỷ văn", "21"),
    Genre("Thanh xuân vườn trường", "95"),
    Genre("Thanh xuyên", "27"),
    Genre("Thể thao", "56"),
    Genre("Thiên kim thật - giả", "183"),
    Genre("Thực tế", "88"),
    Genre("Thương trường", "100"),
    Genre("Tiên hiệp/ Tu tiên", "94"),
    Genre("Tiểu thuyết Hàn Quốc", "164"),
    Genre("Tình chị em - Hồng hài nhi", "35"),
    Genre("Tinh tế/ABO", "86"),
    Genre("Tình yêu thầy trò", "34"),
    Genre("Tình yêu văn phòng", "45"),
    Genre("Tổng hợp", "169"),
    Genre("TQ", "148"),
    Genre("Tranh quyền đoạt vị", "66"),
    Genre("Trap", "160"),
    Genre("Trinh thám - phá án", "103"),
    Genre("Trùng sinh", "52"),
    Genre("Trước ngược nữ sau ngược nam", "127"),
    Genre("Truyện ngắn", "23"),
    Genre("Truyện nước ngoài", "146"),
    Genre("Từ thanh xuân đến trưởng thành", "178"),
    Genre("Tự truyện", "137"),
    Genre("Tương lai", "18"),
    Genre("Tuỳ bút", "22"),
    Genre("Tuỳ thân không gian", "92"),
    Genre("Vả mặt", "170"),
    Genre("Viễn tưởng", "87"),
    Genre("Vô hạn lưu", "186"),
    Genre("Võng du", "99"),
    Genre("Võng phối", "139"),
    Genre("Xã hội đen", "101"),
    Genre("Xúc tu", "156"),
    Genre("Xuyên không", "25"),
    Genre("Xuyên nhanh", "28"),
    Genre("Xuyên sách", "112"),
    Genre("Y thuật - Bác sĩ", "54"),
    Genre("Yêu thầm", "130"),
)
