name: Build Extension

on:
  workflow_dispatch:
    inputs:
      lang:
        description: 'Language'
        required: true
        type: choice
        default: 'vi'
        options:
          - all
          - ar
          - bg
          - ca
          - cs
          - de
          - en
          - es
          - fr
          - id
          - it
          - ja
          - ko
          - pl
          - pt
          - ru
          - th
          - tr
          - uk
          - vi
          - zh
      extension:
        description: 'Extension name'
        required: true
        type: string
        default: ''

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build extension (${{ inputs.lang }}/${{ inputs.extension }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout main branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Prepare signing key
        run: |
          if [ -n "${{ secrets.SIGNING_KEY }}" ]; then
            echo "${{ secrets.SIGNING_KEY }}" | base64 -d > signingkey.jks
          fi

      - name: Build extension
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew -PextensionLanguage=${{ inputs.lang }} ":src:${{ inputs.lang }}:${{ inputs.extension }}:assembleRelease"

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "apk-${{ inputs.lang }}-${{ inputs.extension }}"
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/jar/release/*.jar
            **/build/keiyoushi-source-info.json
          retention-days: 1

      - name: Clean up CI files
        if: always()
        run: rm -f signingkey.jks